# TODO This is only needed because the init-postgres.py script has dependencies
# on FACT_core.
# Many scripts that one would expect to be able to run independently in fact can't
# In the future we should maybe extract these in a pip module
FROM alpine:3.19

RUN apk add --no-cache \
        bash \
        git \
        docker \
        docker-compose \
        postgresql16-client \
        python3 \
        py3-distro \
        py3-pip \
        py3-psutil \
        py3-requests \
        py3-maturin \
        file


#COPY FACT_core /opt/FACT_core

RUN git clone --depth=1 https://github.com/ElDavoo/FACT_core.git /opt/FACT_core

RUN python3 -m venv /opt/FACT_core/venv && \
    /opt/FACT_core/venv/bin/pip install --upgrade \
    pip setuptools debugpy sqlalchemy typing-extensions alembic psycopg2-binary

RUN . /opt/FACT_core/venv/bin/activate  && \ 
    pip install -r /opt/FACT_core/src/install/requirements_pre_install.txt

COPY entrypoint.sh /usr/local/bin/

ENV INSIDE_DOCKER=true
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
