FROM ubuntu:jammy

# Upgrade system and install dependencies of the installer
RUN apt-get -y update && apt-get -y upgrade && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install --no-install-recommends \
        ca-certificates \
        git \
        lsb-release \
        sudo \
        tzdata \
        wget \
        python3 \
        python3-venv \
        python3-pip \
        python3-wheel \
        && \
    apt clean

RUN useradd -r --no-create-home -d /var/log/fact fact && \
    printf 'fact	ALL=(ALL:ALL) NOPASSWD: ALL\n' > /etc/sudoers.d/99_fact && \
    mkdir /opt/FACT_core && chown fact: /opt/FACT_core && \
    mkdir /var/log/fact && chown fact: /var/log/fact

USER fact:fact
WORKDIR /var/log/fact

#ADD http://date.jsontest.com /etc/builddate
RUN git clone --depth=1 https://github.com/ElDavoo/FACT_core.git /opt/FACT_core
#COPY FACT_core/src/install /opt/FACT_core/src/install

RUN python3 -m venv /opt/FACT_core/venv && \
    /opt/FACT_core/venv/bin/pip install --upgrade pip setuptools debugpy

RUN . /opt/FACT_core/venv/bin/activate  && \ 
    /opt/FACT_core/src/install/pre_install.sh

RUN . /opt/FACT_core/venv/bin/activate  && \
    FACT_INSTALLER_SKIP_DOCKER=y python3 /opt/FACT_core/src/install.py --common && \
    sudo apt clean

ENV INSIDE_DOCKER=true
